fconc: fconc.o write_file.o doWrite.o
	gcc -o fconc fconc.o write_file.o doWrite.o

fconc.o: fconc.c
	gcc -Wall -c fconc.c

write_file.o: write_file.c
	gcc -Wall -c write_file.c

doWrite.o: doWrite.c
	gcc -Wall -c doWrite.c
